### ISSUE TITLE
Some questions about Docker

### ISSUE THREAD

**Issue by qimingweng** [rcadena/ebs-docker-hello#1]
Hey, just saw your Youtube video which was great.

I have a question about the Dockerfile (https://github.com/rcadena/ebs-docker-hello/blob/master/Dockerfile), would you be able to explain what each of those three lines do?

In terms of deploying to Elastic Beanstalk, I'm a little confused when the application is compiled; is it compiled before it's zipped and sent to EB or compiled on the EB instance(s)?

**Comment by rcadena** [comment]
Regarding the lines: these are just standard Dockerfile commands.

```
FROM google/golang-runtime 
```
The first one grabs the template image (google/golang-runtime) and bases the new image on this.  
```
EXPOSE 8080
```
Exposes port 8080 from the container. I do this because the go web app listens on port 8080.
```
WORKDIR /gopath/src/app
```
sets the work directory for any subsequent run commands.

These are all standard Dockerfile build commands: https://docs.docker.com/reference/builder/

Regarding your question about build time: compilation happens after the container is built and running.

Note that the Dockerfile in this project points to a docker image that is out-of-date.  See this for the newest image: https://hub.docker.com/_/golang/

I would not use this method for production since there are "simpler" deployment ways to do this, though they are not "simpler" to build.  If you were to deploy a binary, you'd have to compile the go app locally for the target runtime, which might mean either duplicating the runtime platform or cross-compiling.  This is not terribly hard but it's too complicated for a demo like this one, but the setup work is probably worth the investment in easier deployment.  

You might want to take a look at this: https://developer.atlassian.com/blog/2015/07/osx-static-golang-binaries-with-docker/

**Comment by rcadena** [comment]
I'll close this issue now but feel free to ask any further clarifications here.

**Comment by qimingweng** [comment]
Thanks so much for the details! I'm looking into the atlassian article, which is a little steep but I think I get the gist of it.
